FROM rocker/shiny:latest

RUN apt-get update && apt-get install -y \
    libcurl4-openssl-dev \
    libssl-dev \
    libxml2-dev \
    && rm -rf /var/lib/apt/lists/*

RUN R -e "install.packages(c('shinydashboard', 'dplyr', 'shinyWidgets', 'shinyjs', 'DT', 'shiny', 'ggplot2'))"

COPY . /srv/shiny-server/app/

EXPOSE 3838

CMD ["/usr/bin/shiny-server"]
